export default {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_CATEGORY: "SET_CATEGORY",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_ALL_CATEGORIES: "SET_ALL_CATEGORIES",
  SET_SEARCH_KEYWORD: "SET_SEARCH_KEYWORD",
  SET_PAGINATION_INDEX: "SET_PAGINATION_INDEX",
  SET_TOTAL_PRODUCT_AMOUNT: "SET_TOTAL_PRODUCT_AMOUNT",
};
